networks:
  dpi_network:
    driver: bridge

services:
  # 1. Il Livello di Analisi Forense (Python)
  analyzer:
    build:
      context: .
      dockerfile: analyzer-python/Dockerfile
    networks:
      - dpi_network
    
    volumes:
      - ./logs:/app/logs

  # 2. Il Gateway/Router Concorrente (Go)
  router:
    build: ./router-go
    networks:
      - dpi_network
    ports:
      - "8080:8080"  # Porta per ricevere gli stream dal Sensore
      - "8081:8081"  # Porta HTTP per servire la Dashboard Web
    depends_on:
      - analyzer

  # 3. Il Sensore Edge (C++)
  sensor:
    build: 
      context: . 
      dockerfile: sensor-cpp/Dockerfile
    # network_mode: "service:router" fonde lo stack di rete: il sensore può usare "localhost" per raggiungere il router
    network_mode: "service:router"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - router

  # 4. Il Generatore di Traffico (Simulatore per Test)
  generator:
    build: ./traffic-generator
    networks:
      - dpi_network
    # Ritardo di 5 secondi per garantire che Analyzer e Router siano in ascolto prima di iniettare traffico
    command: >
      /bin/sh -c "sleep 5 && python -u generator.py"