// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: packet_data.proto
// Protobuf C++ Version: 7.36.1

#include "packet_data.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::packet_inspector::NetworkPacket
        {&::_pbi::kDescriptorMethods, &::descriptor_table_packet_5fdata_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
namespace packet_inspector {
class NetworkPacket::_Internal {
 public:
  using HasBits = decltype(::std::declval<NetworkPacket>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(NetworkPacket, _impl_._has_bits_);
};

constexpr NetworkPacket::ParseTableT_ NetworkPacket::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(NetworkPacket, _impl_._has_bits_),
      0, // no _extensions_
      7, 56,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967168,  // skipmap
      offsetof(ParseTableT_, field_entries),
      7,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::MpUnknownFields,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::packet_inspector::NetworkPacket>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
      // string source_ip = 1;
      {::_pbi::TcParser::FastUS1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(NetworkPacket, _impl_.source_ip_)}},
      // string dest_ip = 2;
      {::_pbi::TcParser::FastUS1,
       {18, 1, 0,
        PROTOBUF_FIELD_OFFSET(NetworkPacket, _impl_.dest_ip_)}},
      // int32 source_port = 3;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NetworkPacket, _impl_.source_port_), 4>(),
       {24, 4, 0,
        PROTOBUF_FIELD_OFFSET(NetworkPacket, _impl_.source_port_)}},
      // int32 dest_port = 4;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NetworkPacket, _impl_.dest_port_), 5>(),
       {32, 5, 0,
        PROTOBUF_FIELD_OFFSET(NetworkPacket, _impl_.dest_port_)}},
      // string protocol = 5;
      {::_pbi::TcParser::FastUS1,
       {42, 2, 0,
        PROTOBUF_FIELD_OFFSET(NetworkPacket, _impl_.protocol_)}},
      // bytes raw_payload = 6;
      {::_pbi::TcParser::FastBS1,
       {50, 3, 0,
        PROTOBUF_FIELD_OFFSET(NetworkPacket, _impl_.raw_payload_)}},
      // int64 timestamp_ms = 7;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(NetworkPacket, _impl_.timestamp_ms_), 6>(),
       {56, 6, 0,
        PROTOBUF_FIELD_OFFSET(NetworkPacket, _impl_.timestamp_ms_)}},
    }}, {{
      65535, 65535
    }}, {{
      // string source_ip = 1;
      {PROTOBUF_FIELD_OFFSET(NetworkPacket, _impl_.source_ip_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // string dest_ip = 2;
      {PROTOBUF_FIELD_OFFSET(NetworkPacket, _impl_.dest_ip_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // int32 source_port = 3;
      {PROTOBUF_FIELD_OFFSET(NetworkPacket, _impl_.source_port_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
      // int32 dest_port = 4;
      {PROTOBUF_FIELD_OFFSET(NetworkPacket, _impl_.dest_port_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
      // string protocol = 5;
      {PROTOBUF_FIELD_OFFSET(NetworkPacket, _impl_.protocol_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // bytes raw_payload = 6;
      {PROTOBUF_FIELD_OFFSET(NetworkPacket, _impl_.raw_payload_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
      // int64 timestamp_ms = 7;
      {PROTOBUF_FIELD_OFFSET(NetworkPacket, _impl_.timestamp_ms_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    }},
    // no aux_entries
    {{
      "\36\11\7\0\0\10\0\0"
      "packet_inspector.NetworkPacket"
      "source_ip"
      "dest_ip"
      "protocol"
    }},
  };
}


inline constexpr NetworkPacket::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : source_ip_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        dest_ip_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        protocol_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        raw_payload_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        source_port_{0},
        dest_port_{0},
        timestamp_ms_{::int64_t{0}} {}

template <typename>
constexpr NetworkPacket::NetworkPacket(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : Super_(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL NetworkPacket::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) NetworkPacket(arena);
}
constexpr auto NetworkPacket::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(NetworkPacket), alignof(NetworkPacket));
}
constexpr auto NetworkPacket::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &NetworkPacket::MergeImpl,
          Super_::GetNewImpl<NetworkPacket>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &NetworkPacket::SharedDtor,
          Super_::GetClearImpl<NetworkPacket>(), &NetworkPacket::ByteSizeLong,
              &NetworkPacket::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(NetworkPacket, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_packet_5fdata_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct NetworkPacketGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr NetworkPacketGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 NetworkPacket_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(NetworkPacket::InternalGenerateClassData_(
            _default, &NetworkPacket_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<NetworkPacket>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~NetworkPacketGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) NetworkPacket _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<NetworkPacket>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(NetworkPacketGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST NetworkPacketGlobalsTypeInternal NetworkPacket_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* NetworkPacket_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return NetworkPacket_globals_.GetClassData();
#else
  return NetworkPacket_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
}  // namespace packet_inspector
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_packet_5fdata_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_packet_5fdata_2eproto = nullptr;
const ::uint32_t
    TableStruct_packet_5fdata_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::packet_inspector::NetworkPacket, _impl_._has_bits_),
        10, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::packet_inspector::NetworkPacket, _impl_.source_ip_),
        PROTOBUF_FIELD_OFFSET(::packet_inspector::NetworkPacket, _impl_.dest_ip_),
        PROTOBUF_FIELD_OFFSET(::packet_inspector::NetworkPacket, _impl_.source_port_),
        PROTOBUF_FIELD_OFFSET(::packet_inspector::NetworkPacket, _impl_.dest_port_),
        PROTOBUF_FIELD_OFFSET(::packet_inspector::NetworkPacket, _impl_.protocol_),
        PROTOBUF_FIELD_OFFSET(::packet_inspector::NetworkPacket, _impl_.raw_payload_),
        PROTOBUF_FIELD_OFFSET(::packet_inspector::NetworkPacket, _impl_.timestamp_ms_),
        0,
        1,
        4,
        5,
        2,
        3,
        6,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::packet_inspector::NetworkPacket)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::packet_inspector::NetworkPacket_globals_,
};
const char descriptor_table_protodef_packet_5fdata_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021packet_data.proto\022\020packet_inspector\"\230\001"
    "\n\rNetworkPacket\022\021\n\tsource_ip\030\001 \001(\t\022\017\n\007de"
    "st_ip\030\002 \001(\t\022\023\n\013source_port\030\003 \001(\005\022\021\n\tdest"
    "_port\030\004 \001(\005\022\020\n\010protocol\030\005 \001(\t\022\023\n\013raw_pay"
    "load\030\006 \001(\014\022\024\n\014timestamp_ms\030\007 \001(\003B\021Z\017./ro"
    "uter;routerb\006proto3"
};
static ::absl::once_flag descriptor_table_packet_5fdata_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_packet_5fdata_2eproto = {
    false,
    false,
    219,
    descriptor_table_protodef_packet_5fdata_2eproto,
    "packet_data.proto",
    &descriptor_table_packet_5fdata_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_message_globals,
    TableStruct_packet_5fdata_2eproto::offsets,
    file_level_enum_descriptors_packet_5fdata_2eproto,
    file_level_service_descriptors_packet_5fdata_2eproto,
};
namespace packet_inspector {
// ===================================================================

NetworkPacket::NetworkPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, NetworkPacket_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:packet_inspector.NetworkPacket)
}
PROTOBUF_NDEBUG_INLINE NetworkPacket::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::packet_inspector::NetworkPacket& from_msg)
      : _has_bits_{from._has_bits_},
        source_ip_(arena, from.source_ip_),
        dest_ip_(arena, from.dest_ip_),
        protocol_(arena, from.protocol_),
        raw_payload_(arena, from.raw_payload_) {}

NetworkPacket::NetworkPacket(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const NetworkPacket& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, NetworkPacket_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NetworkPacket* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, source_port_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, source_port_),
           offsetof(Impl_, timestamp_ms_) -
               offsetof(Impl_, source_port_) +
               sizeof(Impl_::timestamp_ms_));

  // @@protoc_insertion_point(copy_constructor:packet_inspector.NetworkPacket)
}
PROTOBUF_NDEBUG_INLINE NetworkPacket::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : source_ip_(arena),
        dest_ip_(arena),
        protocol_(arena),
        raw_payload_(arena) {}

inline void NetworkPacket::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, source_port_),
           0,
           offsetof(Impl_, timestamp_ms_) -
               offsetof(Impl_, source_port_) +
               sizeof(Impl_::timestamp_ms_));
}
NetworkPacket::~NetworkPacket() {
  // @@protoc_insertion_point(destructor:packet_inspector.NetworkPacket)
  SharedDtor(*this);
}
inline void NetworkPacket::SharedDtor(MessageLite& self) {
  NetworkPacket& this_ = static_cast<NetworkPacket&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.source_ip_.Destroy();
  this_._impl_.dest_ip_.Destroy();
  this_._impl_.protocol_.Destroy();
  this_._impl_.raw_payload_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull NetworkPacket_class_data_ =
        NetworkPacket::InternalGenerateClassData_(NetworkPacket_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NetworkPacket::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NetworkPacket_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(NetworkPacket_class_data_.tc_table);
  return NetworkPacket_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NetworkPacket::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NetworkPacket_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&NetworkPacket_globals_));
  return NetworkPacket_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const NetworkPacket::ParseTableT_
    NetworkPacket::_table_ =
        NetworkPacket::InternalGenerateParseTable_(NetworkPacket_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void NetworkPacket::Clear() {
  auto& this_ [[maybe_unused]] = *this;
  // @@protoc_insertion_point(message_clear_start:packet_inspector.NetworkPacket)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      this_._impl_.source_ip_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      this_._impl_.dest_ip_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      this_._impl_.protocol_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      this_._impl_.raw_payload_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000070U)) {
    ::memset(&this_._impl_.source_port_, 0,
             static_cast<::size_t>(
                 reinterpret_cast<char*>(&this_._impl_.timestamp_ms_) -
                 reinterpret_cast<char*>(&this_._impl_.source_port_)) +
                 sizeof(_impl_.timestamp_ms_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL NetworkPacket::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const NetworkPacket& this_ = static_cast<const NetworkPacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL NetworkPacket::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const NetworkPacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:packet_inspector.NetworkPacket)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string source_ip = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_source_ip().empty()) {
      const ::std::string& _s = this_._internal_source_ip();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "packet_inspector.NetworkPacket.source_ip");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string dest_ip = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_dest_ip().empty()) {
      const ::std::string& _s = this_._internal_dest_ip();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "packet_inspector.NetworkPacket.dest_ip");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // int32 source_port = 3;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_source_port() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_source_port(), target);
    }
  }

  // int32 dest_port = 4;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_dest_port() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<4>(
              stream, this_._internal_dest_port(), target);
    }
  }

  // string protocol = 5;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_protocol().empty()) {
      const ::std::string& _s = this_._internal_protocol();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "packet_inspector.NetworkPacket.protocol");
      target = stream->WriteStringMaybeAliased(5, _s, target);
    }
  }

  // bytes raw_payload = 6;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (!this_._internal_raw_payload().empty()) {
      const ::std::string& _s = this_._internal_raw_payload();
      target = stream->WriteBytesMaybeAliased(6, _s, target);
    }
  }

  // int64 timestamp_ms = 7;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (this_._internal_timestamp_ms() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<7>(
              stream, this_._internal_timestamp_ms(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:packet_inspector.NetworkPacket)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t NetworkPacket::ByteSizeLong(const MessageLite& base) {
  const NetworkPacket& this_ = static_cast<const NetworkPacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t NetworkPacket::ByteSizeLong() const {
  const NetworkPacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:packet_inspector.NetworkPacket)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    // string source_ip = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_source_ip().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_source_ip());
      }
    }
    // string dest_ip = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_dest_ip().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_dest_ip());
      }
    }
    // string protocol = 5;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_protocol().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_protocol());
      }
    }
    // bytes raw_payload = 6;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!this_._internal_raw_payload().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_raw_payload());
      }
    }
    // int32 source_port = 3;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_source_port() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_source_port());
      }
    }
    // int32 dest_port = 4;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_dest_port() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_dest_port());
      }
    }
    // int64 timestamp_ms = 7;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (this_._internal_timestamp_ms() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_timestamp_ms());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void NetworkPacket::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<NetworkPacket*>(&to_msg);
  auto& from = static_cast<const NetworkPacket&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:packet_inspector.NetworkPacket)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_source_ip().empty()) {
        _this->_internal_set_source_ip(from._internal_source_ip());
      } else {
        if (_this->_impl_.source_ip_.IsDefault()) {
          _this->_internal_set_source_ip("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_dest_ip().empty()) {
        _this->_internal_set_dest_ip(from._internal_dest_ip());
      } else {
        if (_this->_impl_.dest_ip_.IsDefault()) {
          _this->_internal_set_dest_ip("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_protocol().empty()) {
        _this->_internal_set_protocol(from._internal_protocol());
      } else {
        if (_this->_impl_.protocol_.IsDefault()) {
          _this->_internal_set_protocol("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!from._internal_raw_payload().empty()) {
        _this->_internal_set_raw_payload(from._internal_raw_payload());
      } else {
        if (_this->_impl_.raw_payload_.IsDefault()) {
          _this->_internal_set_raw_payload("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_source_port() != 0) {
        _this->_impl_.source_port_ = from._impl_.source_port_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_dest_port() != 0) {
        _this->_impl_.dest_port_ = from._impl_.dest_port_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (from._internal_timestamp_ms() != 0) {
        _this->_impl_.timestamp_ms_ = from._impl_.timestamp_ms_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void NetworkPacket::CopyFrom(const NetworkPacket& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:packet_inspector.NetworkPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NetworkPacket::InternalSwap(NetworkPacket* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.source_ip_, &other->_impl_.source_ip_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.dest_ip_, &other->_impl_.dest_ip_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.protocol_, &other->_impl_.protocol_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.raw_payload_, &other->_impl_.raw_payload_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(NetworkPacket, _impl_.timestamp_ms_)
      + sizeof(NetworkPacket::_impl_.timestamp_ms_)
      - PROTOBUF_FIELD_OFFSET(NetworkPacket, _impl_.source_port_)>(
          reinterpret_cast<char*>(&_impl_.source_port_),
          reinterpret_cast<char*>(&other->_impl_.source_port_));
}

::google::protobuf::Metadata NetworkPacket::GetMetadata() const {
  return Super_::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace packet_inspector
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_packet_5fdata_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
