// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: packet_data.proto
// Protobuf C++ Version: 7.36.1

#ifndef packet_5fdata_2eproto_2epb_2eh
#define packet_5fdata_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7036001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_packet_5fdata_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_packet_5fdata_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_packet_5fdata_2eproto;
}  // extern "C"
namespace packet_inspector {
class NetworkPacket;
struct NetworkPacketGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern NetworkPacketGlobalsTypeInternal NetworkPacket_globals_;
extern const ::google::protobuf::internal::ClassDataFull NetworkPacket_class_data_;
#else
extern const NetworkPacketGlobalsTypeInternal NetworkPacket_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
}  // namespace packet_inspector
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace packet_inspector {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED NetworkPacket final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:packet_inspector.NetworkPacket) */ {
  using Super_ = ::google::protobuf::Message;

 public:
  inline NetworkPacket() : NetworkPacket(nullptr) {}
  ~NetworkPacket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(NetworkPacket* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(NetworkPacket));
  }
#endif

  template <typename = void>
  explicit constexpr NetworkPacket(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline NetworkPacket(const NetworkPacket& from) : NetworkPacket(nullptr, from) {}
  inline NetworkPacket(NetworkPacket&& from) noexcept : NetworkPacket(nullptr, ::std::move(from)) {}
  inline NetworkPacket& operator=(const NetworkPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline NetworkPacket& operator=(NetworkPacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const NetworkPacket& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<NetworkPacket>(&NetworkPacket_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(NetworkPacket& a, NetworkPacket& b) { a.Swap(&b); }
  inline void Swap(NetworkPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NetworkPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] NetworkPacket* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return Super_::DefaultConstruct<NetworkPacket>(arena);
  }
  using Super_::CopyFrom;
  void CopyFrom(const NetworkPacket& from);
  using Super_::MergeFrom;
  void MergeFrom(const NetworkPacket& from) { NetworkPacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(NetworkPacket* PROTOBUF_NONNULL other);
 private:
  static ::absl::string_view FullMessageName() { return "packet_inspector.NetworkPacket"; }

  explicit NetworkPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  NetworkPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const NetworkPacket& from);
  NetworkPacket(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, NetworkPacket&& from) noexcept
      : NetworkPacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSourceIpFieldNumber = 1,
    kDestIpFieldNumber = 2,
    kProtocolFieldNumber = 5,
    kRawPayloadFieldNumber = 6,
    kSourcePortFieldNumber = 3,
    kDestPortFieldNumber = 4,
    kTimestampMsFieldNumber = 7,
  };
  // string source_ip = 1;
  void clear_source_ip() ;
  [[nodiscard]] const ::std::string& source_ip() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_source_ip(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_source_ip();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_source_ip();
  void set_allocated_source_ip(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_source_ip() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_source_ip(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_source_ip();

  public:
  // string dest_ip = 2;
  void clear_dest_ip() ;
  [[nodiscard]] const ::std::string& dest_ip() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_dest_ip(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_dest_ip();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_dest_ip();
  void set_allocated_dest_ip(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_dest_ip() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_dest_ip(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_dest_ip();

  public:
  // string protocol = 5;
  void clear_protocol() ;
  [[nodiscard]] const ::std::string& protocol() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_protocol(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_protocol();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_protocol();
  void set_allocated_protocol(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_protocol() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_protocol(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_protocol();

  public:
  // bytes raw_payload = 6;
  void clear_raw_payload() ;
  [[nodiscard]] const ::std::string& raw_payload() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_raw_payload(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_raw_payload();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_raw_payload();
  void set_allocated_raw_payload(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_raw_payload() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_raw_payload(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_raw_payload();

  public:
  // int32 source_port = 3;
  void clear_source_port() ;
  [[nodiscard]] ::int32_t source_port() const;
  void set_source_port(::int32_t value);

  private:
  ::int32_t _internal_source_port() const;
  void _internal_set_source_port(::int32_t value);

  public:
  // int32 dest_port = 4;
  void clear_dest_port() ;
  [[nodiscard]] ::int32_t dest_port() const;
  void set_dest_port(::int32_t value);

  private:
  ::int32_t _internal_dest_port() const;
  void _internal_set_dest_port(::int32_t value);

  public:
  // int64 timestamp_ms = 7;
  void clear_timestamp_ms() ;
  [[nodiscard]] ::int64_t timestamp_ms() const;
  void set_timestamp_ms(::int64_t value);

  private:
  ::int64_t _internal_timestamp_ms() const;
  void _internal_set_timestamp_ms(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:packet_inspector.NetworkPacket)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<3, 7,
                          0, 63,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const NetworkPacket& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr source_ip_;
    ::google::protobuf::internal::ArenaStringPtr dest_ip_;
    ::google::protobuf::internal::ArenaStringPtr protocol_;
    ::google::protobuf::internal::ArenaStringPtr raw_payload_;
    ::int32_t source_port_;
    ::int32_t dest_port_;
    ::int64_t timestamp_ms_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packet_5fdata_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// NetworkPacket

// string source_ip = 1;
inline void NetworkPacket::clear_source_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_ip_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& NetworkPacket::source_ip() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:packet_inspector.NetworkPacket.source_ip)
  return _internal_source_ip();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void NetworkPacket::set_source_ip(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.source_ip_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:packet_inspector.NetworkPacket.source_ip)
}
inline ::std::string* PROTOBUF_NONNULL NetworkPacket::mutable_source_ip()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_source_ip();
  // @@protoc_insertion_point(field_mutable:packet_inspector.NetworkPacket.source_ip)
  return _s;
}
inline const ::std::string& NetworkPacket::_internal_source_ip() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.source_ip_.Get();
}
inline void NetworkPacket::_internal_set_source_ip(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_ip_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL NetworkPacket::_internal_mutable_source_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.source_ip_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE NetworkPacket::release_source_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:packet_inspector.NetworkPacket.source_ip)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.source_ip_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.source_ip_.Set("", GetArena());
  }
  return released;
}
inline void NetworkPacket::set_allocated_source_ip(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.source_ip_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.source_ip_.IsDefault()) {
    _impl_.source_ip_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:packet_inspector.NetworkPacket.source_ip)
}

// string dest_ip = 2;
inline void NetworkPacket::clear_dest_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dest_ip_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::std::string& NetworkPacket::dest_ip() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:packet_inspector.NetworkPacket.dest_ip)
  return _internal_dest_ip();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void NetworkPacket::set_dest_ip(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.dest_ip_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:packet_inspector.NetworkPacket.dest_ip)
}
inline ::std::string* PROTOBUF_NONNULL NetworkPacket::mutable_dest_ip()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_dest_ip();
  // @@protoc_insertion_point(field_mutable:packet_inspector.NetworkPacket.dest_ip)
  return _s;
}
inline const ::std::string& NetworkPacket::_internal_dest_ip() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dest_ip_.Get();
}
inline void NetworkPacket::_internal_set_dest_ip(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dest_ip_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL NetworkPacket::_internal_mutable_dest_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.dest_ip_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE NetworkPacket::release_dest_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:packet_inspector.NetworkPacket.dest_ip)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.dest_ip_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.dest_ip_.Set("", GetArena());
  }
  return released;
}
inline void NetworkPacket::set_allocated_dest_ip(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.dest_ip_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.dest_ip_.IsDefault()) {
    _impl_.dest_ip_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:packet_inspector.NetworkPacket.dest_ip)
}

// int32 source_port = 3;
inline void NetworkPacket::clear_source_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_port_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
}
inline ::int32_t NetworkPacket::source_port() const {
  // @@protoc_insertion_point(field_get:packet_inspector.NetworkPacket.source_port)
  return _internal_source_port();
}
inline void NetworkPacket::set_source_port(::int32_t value) {
  _internal_set_source_port(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:packet_inspector.NetworkPacket.source_port)
}
inline ::int32_t NetworkPacket::_internal_source_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.source_port_;
}
inline void NetworkPacket::_internal_set_source_port(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_port_ = value;
}

// int32 dest_port = 4;
inline void NetworkPacket::clear_dest_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dest_port_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
}
inline ::int32_t NetworkPacket::dest_port() const {
  // @@protoc_insertion_point(field_get:packet_inspector.NetworkPacket.dest_port)
  return _internal_dest_port();
}
inline void NetworkPacket::set_dest_port(::int32_t value) {
  _internal_set_dest_port(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:packet_inspector.NetworkPacket.dest_port)
}
inline ::int32_t NetworkPacket::_internal_dest_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dest_port_;
}
inline void NetworkPacket::_internal_set_dest_port(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dest_port_ = value;
}

// string protocol = 5;
inline void NetworkPacket::clear_protocol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.protocol_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline const ::std::string& NetworkPacket::protocol() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:packet_inspector.NetworkPacket.protocol)
  return _internal_protocol();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void NetworkPacket::set_protocol(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.protocol_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:packet_inspector.NetworkPacket.protocol)
}
inline ::std::string* PROTOBUF_NONNULL NetworkPacket::mutable_protocol()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_protocol();
  // @@protoc_insertion_point(field_mutable:packet_inspector.NetworkPacket.protocol)
  return _s;
}
inline const ::std::string& NetworkPacket::_internal_protocol() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.protocol_.Get();
}
inline void NetworkPacket::_internal_set_protocol(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.protocol_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL NetworkPacket::_internal_mutable_protocol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.protocol_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE NetworkPacket::release_protocol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:packet_inspector.NetworkPacket.protocol)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.protocol_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.protocol_.Set("", GetArena());
  }
  return released;
}
inline void NetworkPacket::set_allocated_protocol(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.protocol_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.protocol_.IsDefault()) {
    _impl_.protocol_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:packet_inspector.NetworkPacket.protocol)
}

// bytes raw_payload = 6;
inline void NetworkPacket::clear_raw_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.raw_payload_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
inline const ::std::string& NetworkPacket::raw_payload() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:packet_inspector.NetworkPacket.raw_payload)
  return _internal_raw_payload();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void NetworkPacket::set_raw_payload(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.raw_payload_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:packet_inspector.NetworkPacket.raw_payload)
}
inline ::std::string* PROTOBUF_NONNULL NetworkPacket::mutable_raw_payload()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_raw_payload();
  // @@protoc_insertion_point(field_mutable:packet_inspector.NetworkPacket.raw_payload)
  return _s;
}
inline const ::std::string& NetworkPacket::_internal_raw_payload() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.raw_payload_.Get();
}
inline void NetworkPacket::_internal_set_raw_payload(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.raw_payload_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL NetworkPacket::_internal_mutable_raw_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.raw_payload_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE NetworkPacket::release_raw_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:packet_inspector.NetworkPacket.raw_payload)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.raw_payload_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.raw_payload_.Set("", GetArena());
  }
  return released;
}
inline void NetworkPacket::set_allocated_raw_payload(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.raw_payload_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.raw_payload_.IsDefault()) {
    _impl_.raw_payload_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:packet_inspector.NetworkPacket.raw_payload)
}

// int64 timestamp_ms = 7;
inline void NetworkPacket::clear_timestamp_ms() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ms_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
}
inline ::int64_t NetworkPacket::timestamp_ms() const {
  // @@protoc_insertion_point(field_get:packet_inspector.NetworkPacket.timestamp_ms)
  return _internal_timestamp_ms();
}
inline void NetworkPacket::set_timestamp_ms(::int64_t value) {
  _internal_set_timestamp_ms(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:packet_inspector.NetworkPacket.timestamp_ms)
}
inline ::int64_t NetworkPacket::_internal_timestamp_ms() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_ms_;
}
inline void NetworkPacket::_internal_set_timestamp_ms(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ms_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace packet_inspector


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // packet_5fdata_2eproto_2epb_2eh
