// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: packet_data.proto

package router

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// La struttura esatta del pacchetto che i tre linguaggi si scambieranno
type NetworkPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceIp      string                 `protobuf:"bytes,1,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	DestIp        string                 `protobuf:"bytes,2,opt,name=dest_ip,json=destIp,proto3" json:"dest_ip,omitempty"`
	SourcePort    int32                  `protobuf:"varint,3,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	DestPort      int32                  `protobuf:"varint,4,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`                           // Es: "TCP", "UDP"
	RawPayload    []byte                 `protobuf:"bytes,6,opt,name=raw_payload,json=rawPayload,proto3" json:"raw_payload,omitempty"`     // I dati veri e propri (dove cercheremo le password)
	TimestampMs   int64                  `protobuf:"varint,7,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"` // Timestamp per calcolare le latenze
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPacket) Reset() {
	*x = NetworkPacket{}
	mi := &file_packet_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPacket) ProtoMessage() {}

func (x *NetworkPacket) ProtoReflect() protoreflect.Message {
	mi := &file_packet_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPacket.ProtoReflect.Descriptor instead.
func (*NetworkPacket) Descriptor() ([]byte, []int) {
	return file_packet_data_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkPacket) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *NetworkPacket) GetDestIp() string {
	if x != nil {
		return x.DestIp
	}
	return ""
}

func (x *NetworkPacket) GetSourcePort() int32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

func (x *NetworkPacket) GetDestPort() int32 {
	if x != nil {
		return x.DestPort
	}
	return 0
}

func (x *NetworkPacket) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NetworkPacket) GetRawPayload() []byte {
	if x != nil {
		return x.RawPayload
	}
	return nil
}

func (x *NetworkPacket) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

var File_packet_data_proto protoreflect.FileDescriptor

const file_packet_data_proto_rawDesc = "" +
	"\n" +
	"\x11packet_data.proto\x12\x10packet_inspector\"\xe3\x01\n" +
	"\rNetworkPacket\x12\x1b\n" +
	"\tsource_ip\x18\x01 \x01(\tR\bsourceIp\x12\x17\n" +
	"\adest_ip\x18\x02 \x01(\tR\x06destIp\x12\x1f\n" +
	"\vsource_port\x18\x03 \x01(\x05R\n" +
	"sourcePort\x12\x1b\n" +
	"\tdest_port\x18\x04 \x01(\x05R\bdestPort\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12\x1f\n" +
	"\vraw_payload\x18\x06 \x01(\fR\n" +
	"rawPayload\x12!\n" +
	"\ftimestamp_ms\x18\a \x01(\x03R\vtimestampMsB\x11Z\x0f./router;routerb\x06proto3"

var (
	file_packet_data_proto_rawDescOnce sync.Once
	file_packet_data_proto_rawDescData []byte
)

func file_packet_data_proto_rawDescGZIP() []byte {
	file_packet_data_proto_rawDescOnce.Do(func() {
		file_packet_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_data_proto_rawDesc), len(file_packet_data_proto_rawDesc)))
	})
	return file_packet_data_proto_rawDescData
}

var file_packet_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packet_data_proto_goTypes = []any{
	(*NetworkPacket)(nil), // 0: packet_inspector.NetworkPacket
}
var file_packet_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_packet_data_proto_init() }
func file_packet_data_proto_init() {
	if File_packet_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_data_proto_rawDesc), len(file_packet_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_data_proto_goTypes,
		DependencyIndexes: file_packet_data_proto_depIdxs,
		MessageInfos:      file_packet_data_proto_msgTypes,
	}.Build()
	File_packet_data_proto = out.File
	file_packet_data_proto_goTypes = nil
	file_packet_data_proto_depIdxs = nil
}
